config/routes.rb
Rails.application.routes.draw do
  get 'date/index'
  get 'date/latest'
  get 'date/oldest'
  get 'date/current-date'
  get 'date/', to: 'date#index', as: 'date'
  get 'category/index'
  get 'category/video-games'
  get 'category/movies'
  get 'category/comics'
  get 'category/books'
  get 'category/tech'
  get 'category/entertainment'
  get 'category/science'
  get 'category/lifestyle'
  get 'category/', to: 'category#index', as: 'category'
  get 'custom_article/index'
  get 'morse_interpreter/index'
  get 'test/index'
  get 'test/thumb'
  get 'test/full'
  get 'main_page/index'
  get 'morse_interpreter/', to: 'morse_interpreter#index', as: 'morse_interpreter'
  resources :articles
  resources :authors
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "main_page#index"

end

app/models/author.rb
class Author < ApplicationRecord
    has_one_attached :avatar

    scope :search, -> (term) {
        where("name LIKE ?", 
            "%#{term}%") 
        }
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]

  # GET /authors or /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: "#{@author.name} was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice:  "#{@author.name} was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_path, status: :see_other, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:name, :contact, :description, :avatar)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_author.html.erb
<div id="<%= dom_id author %>" class="author-container">
  <div class="author-info">
    <p class="author-name">
      <%= author.name %>
    </p>

    <p>
      <%= image_tag(author.avatar, :style=>"width:150px; height: 150px") if author.avatar  %>
    </p>

    <p class="author-contact-info">
      <%= author.contact %>
    </p>

    <p class="author-description">
      <%= author.description %>
    </p>

    <p style="color: green"><%= notice %></p>    
  </div>

  <div id="articles" class="author-articles">
      <h2><%= author.name %>'s Articles</h2>
      <% @articles = Article.by_author_id(author.id) %>
      <%= render "common/article-list" %>
    </div>


</div>

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
  <% if author.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label "#{:name}:", style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label "#{:contact}:", style: "display: block" %>
    <%= form.text_field :contact %>
  </div>

  <div>
    <%= form.label "#{:description}:", style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <%= form.label "#{:image}:", style: "display: block" %>
  <br>
  <%= form.file_field :avatar, accept: "image/* " %>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/authors/edit.html.erb
<h1>Edit <%= @author.name %></h1>

<%= form_with model: @author do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :contact %>
  <%= form.text_field :contact %>

  <%= form.label :description %>
  <%= form.text_field :description %>

  <%= form.file_field :avatar, accept: "image/*" %>
  <%= form.submit %>
<% end %>
<br>

<div>
  <%= link_to "Back to authors", authors_path %>
</div>

app/views/authors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Authors</h1>

<div id="authors">
  <% @authors.each do |author| %>
    <%= render author %>
    <p>
      <%= link_to "Show this author", author %>
    </p>
  <% end %>
</div>

<%= link_to "New author", new_author_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render "form", author: @author %>

<div>
  <%= link_to "Back to authors", authors_path %>
</div>

app/views/authors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @author %>

<div>
  <%= link_to "Edit", edit_author_path(@author) %> |
  <%= link_to "Back to authors", authors_path %>

  <p>
    <%= button_to("Delete", @author, method: :delete, :style => 'color: red') %>
  </p>
</div>